/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Rodrigo
 */
public class ConsultaPapel extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaPapel
     */
    public ConsultaPapel() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        Fondo fondo = new Fondo();
        Dimension size = this.getSize();
        fondo.setSize(size);
        add(fondo);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/logo.png"));


        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        __CANCELARCONMOV = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        __clvDesdeMov2 = new javax.swing.JTextField();
        __dateDesdeMov1 = new com.toedter.calendar.JDateChooser();
        __chkMarca9 = new javax.swing.JCheckBox();
        __dateDesdeMov = new com.toedter.calendar.JDateChooser();
        __chkMarca8 = new javax.swing.JCheckBox();
        __grpPapel = new javax.swing.ButtonGroup();
        __grpMovimiento = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        __etqFechaConMov = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        __optSalida = new javax.swing.JRadioButton();
        __optNinguno = new javax.swing.JRadioButton();
        __optSalidaInterna = new javax.swing.JRadioButton();
        __optEntrada = new javax.swing.JRadioButton();
        __cmbColor = new javax.swing.JComboBox();
        __cmbPropi = new javax.swing.JComboBox();
        __chkKiloHoja = new javax.swing.JCheckBox();
        __cmbBobinaPaq = new javax.swing.JComboBox();
        __kilohojas = new javax.swing.JTextField();
        __chkFolio = new javax.swing.JCheckBox();
        __bobinapaq = new javax.swing.JTextField();
        __cmbKiloHoja = new javax.swing.JComboBox();
        __folio = new javax.swing.JTextField();
        __chkAlto = new javax.swing.JCheckBox();
        __chkOrdenC = new javax.swing.JCheckBox();
        __grspts = new javax.swing.JTextField();
        __chkBobinaPaq = new javax.swing.JCheckBox();
        __chkClavePapel = new javax.swing.JCheckBox();
        __OrdenP = new javax.swing.JTextField();
        __alto = new javax.swing.JTextField();
        __cmbMarca = new javax.swing.JComboBox();
        __ancho = new javax.swing.JTextField();
        __chkColor = new javax.swing.JCheckBox();
        __chkNombrePapel = new javax.swing.JCheckBox();
        __cmbNombrePapel = new javax.swing.JComboBox();
        __SALIRCONSULTA = new javax.swing.JButton();
        __ACEPTARCONSULTA = new javax.swing.JButton();
        __chkMarca = new javax.swing.JCheckBox();
        __chkProveedor = new javax.swing.JCheckBox();
        __dateIni = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        __Bobina = new javax.swing.JRadioButton();
        __Hoja = new javax.swing.JRadioButton();
        __PapelNingun = new javax.swing.JRadioButton();
        __cmbProveedor = new javax.swing.JComboBox();
        __chkOrdenP = new javax.swing.JCheckBox();
        __OrdenC = new javax.swing.JTextField();
        __chkAncho = new javax.swing.JCheckBox();
        jPanel11 = new javax.swing.JPanel();
        __chkTurno1 = new javax.swing.JCheckBox();
        __chkTurno2 = new javax.swing.JCheckBox();
        __chkTurno3 = new javax.swing.JCheckBox();
        __clave = new javax.swing.JTextField();
        __chkGrsPts = new javax.swing.JCheckBox();
        __chkFechaIni = new javax.swing.JCheckBox();
        __chkPropietario = new javax.swing.JCheckBox();
        __chkTipoEntrada = new javax.swing.JCheckBox();
        __cmbTipoEntrada = new javax.swing.JComboBox();
        __datefin = new com.toedter.calendar.JDateChooser();
        __chkFechaFin = new javax.swing.JCheckBox();
        __cmbTipoSalida = new javax.swing.JComboBox();
        __chkTipoSalida = new javax.swing.JCheckBox();
        __documento = new javax.swing.JTextField();
        __chkDocumento = new javax.swing.JCheckBox();
        __foliohasta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        __MenuConsulta = new javax.swing.JMenuBar();
        __Archivo = new javax.swing.JMenu();
        __menuMovimientosPapel = new javax.swing.JMenuItem();
        __menuRegresar = new javax.swing.JMenuItem();
        __menuAltaPapel = new javax.swing.JMenuItem();
        __menuGeneraReporte = new javax.swing.JMenuItem();
        __MenuAbrirArchivo3 = new javax.swing.JMenuItem();
        __CerrarSesion = new javax.swing.JMenuItem();
        __menuSalirSistema = new javax.swing.JMenuItem();
        __Edicion = new javax.swing.JMenu();
        __menuEdiCambiarFecha = new javax.swing.JMenuItem();
        __menuEdiNewUsuario = new javax.swing.JMenuItem();
        __menuEdiCambiarContraseña = new javax.swing.JMenuItem();
        __menuEdiReporteUsuario = new javax.swing.JMenuItem();
        __menucerrarsesiones = new javax.swing.JMenuItem();
        __menuEdiAcerca = new javax.swing.JMenuItem();
        __menuBackup = new javax.swing.JMenuItem();

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Turno:"));

        jCheckBox7.setText("Turno 1");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setText("Turno 2");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox9.setText("Turno 3");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox7))
                .addGap(28, 28, 28))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox9))
        );

        __CANCELARCONMOV.setText("Cancelar");
        __CANCELARCONMOV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __CANCELARCONMOVActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel21.setText("Clave de Papel:");

        __clvDesdeMov2.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N

        __chkMarca9.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkMarca9.setText("Fecha Final:");

        __chkMarca8.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkMarca8.setText("Fecha Inicial:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Consulta de Papel");
        setIconImage(getIconImage());

        jPanel1.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Para Realizar la Consulta Ingresa los Parametros que Necesitas");

        __etqFechaConMov.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        __etqFechaConMov.setForeground(new java.awt.Color(255, 255, 255));
        __etqFechaConMov.setText("DD/MM/AAAA");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Movimiento:"));
        jPanel9.setOpaque(false);

        __grpMovimiento.add(__optSalida);
        __optSalida.setForeground(new java.awt.Color(255, 255, 255));
        __optSalida.setText("Salida");
        __optSalida.setNextFocusableComponent(__chkClavePapel);

        __grpMovimiento.add(__optNinguno);
        __optNinguno.setForeground(new java.awt.Color(255, 255, 255));
        __optNinguno.setSelected(true);
        __optNinguno.setText("Ninguno");

        __grpMovimiento.add(__optSalidaInterna);
        __optSalidaInterna.setForeground(new java.awt.Color(255, 255, 255));
        __optSalidaInterna.setText("Salidas internas");
        __optSalidaInterna.setNextFocusableComponent(__chkClavePapel);

        __grpMovimiento.add(__optEntrada);
        __optEntrada.setForeground(new java.awt.Color(255, 255, 255));
        __optEntrada.setText("Entrada");
        __optEntrada.setNextFocusableComponent(__optSalida);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__optNinguno)
                    .addComponent(__optSalida))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__optSalidaInterna)
                    .addComponent(__optEntrada))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__optNinguno)
                    .addComponent(__optEntrada))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__optSalidaInterna)
                    .addComponent(__optSalida))
                .addContainerGap())
        );

        __cmbColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmbColor.setEnabled(false);
        __cmbColor.setNextFocusableComponent(__chkMarca);
        __cmbColor.setOpaque(false);
        __cmbColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbColorActionPerformed(evt);
            }
        });

        __cmbPropi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmbPropi.setEnabled(false);
        __cmbPropi.setNextFocusableComponent(__chkKiloHoja);
        __cmbPropi.setOpaque(false);
        __cmbPropi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbPropiActionPerformed(evt);
            }
        });

        __chkKiloHoja.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkKiloHoja.setForeground(new java.awt.Color(255, 255, 255));
        __chkKiloHoja.setSelected(true);
        __chkKiloHoja.setText("Kilos/Hojas :");
        __chkKiloHoja.setEnabled(false);
        __chkKiloHoja.setNextFocusableComponent(__cmbKiloHoja);

        __cmbBobinaPaq.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ">", "<", "=", "" }));
        __cmbBobinaPaq.setEnabled(false);
        __cmbBobinaPaq.setNextFocusableComponent(__bobinapaq);
        __cmbBobinaPaq.setOpaque(false);
        __cmbBobinaPaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbBobinaPaqActionPerformed(evt);
            }
        });

        __kilohojas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __kilohojas.setEnabled(false);
        __kilohojas.setNextFocusableComponent(__chkBobinaPaq);

        __chkFolio.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkFolio.setForeground(new java.awt.Color(255, 255, 255));
        __chkFolio.setSelected(true);
        __chkFolio.setText("Folio Desde:");
        __chkFolio.setEnabled(false);
        __chkFolio.setNextFocusableComponent(__folio);
        __chkFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkFolioActionPerformed(evt);
            }
        });

        __bobinapaq.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __bobinapaq.setEnabled(false);
        __bobinapaq.setNextFocusableComponent(__chkFolio);

        __cmbKiloHoja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ">", "<", "=" }));
        __cmbKiloHoja.setEnabled(false);
        __cmbKiloHoja.setNextFocusableComponent(__kilohojas);
        __cmbKiloHoja.setOpaque(false);
        __cmbKiloHoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbKiloHojaActionPerformed(evt);
            }
        });

        __folio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __folio.setEnabled(false);
        __folio.setNextFocusableComponent(__foliohasta);

        __chkAlto.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkAlto.setForeground(new java.awt.Color(255, 255, 255));
        __chkAlto.setSelected(true);
        __chkAlto.setText("Alto:");
        __chkAlto.setEnabled(false);
        __chkAlto.setNextFocusableComponent(__alto);

        __chkOrdenC.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkOrdenC.setForeground(new java.awt.Color(255, 255, 255));
        __chkOrdenC.setSelected(true);
        __chkOrdenC.setText("Orden de Compra:");
        __chkOrdenC.setEnabled(false);
        __chkOrdenC.setNextFocusableComponent(__OrdenC);

        __grspts.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __grspts.setEnabled(false);
        __grspts.setNextFocusableComponent(__chkColor);

        __chkBobinaPaq.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkBobinaPaq.setForeground(new java.awt.Color(255, 255, 255));
        __chkBobinaPaq.setSelected(true);
        __chkBobinaPaq.setText("Bobinas/Paq:");
        __chkBobinaPaq.setEnabled(false);
        __chkBobinaPaq.setNextFocusableComponent(__cmbBobinaPaq);

        __chkClavePapel.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkClavePapel.setForeground(new java.awt.Color(255, 255, 255));
        __chkClavePapel.setSelected(true);
        __chkClavePapel.setText("Clave de Papel:");
        __chkClavePapel.setEnabled(false);
        __chkClavePapel.setNextFocusableComponent(__clave);
        __chkClavePapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkClavePapelActionPerformed(evt);
            }
        });

        __OrdenP.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __OrdenP.setEnabled(false);
        __OrdenP.setNextFocusableComponent(__chkOrdenC);
        __OrdenP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __OrdenPActionPerformed(evt);
            }
        });

        __alto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __alto.setEnabled(false);
        __alto.setNextFocusableComponent(__chkGrsPts);
        __alto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __altoActionPerformed(evt);
            }
        });

        __cmbMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmbMarca.setEnabled(false);
        __cmbMarca.setNextFocusableComponent(__chkFechaIni);
        __cmbMarca.setOpaque(false);
        __cmbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbMarcaActionPerformed(evt);
            }
        });

        __ancho.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __ancho.setEnabled(false);
        __ancho.setNextFocusableComponent(__chkAlto);

        __chkColor.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkColor.setForeground(new java.awt.Color(255, 255, 255));
        __chkColor.setSelected(true);
        __chkColor.setText("Color:");
        __chkColor.setEnabled(false);
        __chkColor.setNextFocusableComponent(__cmbColor);

        __chkNombrePapel.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkNombrePapel.setForeground(new java.awt.Color(255, 255, 255));
        __chkNombrePapel.setSelected(true);
        __chkNombrePapel.setText("Nombre de Papel:");
        __chkNombrePapel.setEnabled(false);
        __chkNombrePapel.setNextFocusableComponent(__cmbNombrePapel);

        __cmbNombrePapel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmbNombrePapel.setEnabled(false);
        __cmbNombrePapel.setNextFocusableComponent(__chkAncho);
        __cmbNombrePapel.setOpaque(false);
        __cmbNombrePapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbNombrePapelActionPerformed(evt);
            }
        });

        __SALIRCONSULTA.setText("CANCELAR");
        __SALIRCONSULTA.setNextFocusableComponent(__ACEPTARCONSULTA);
        __SALIRCONSULTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __SALIRCONSULTAActionPerformed(evt);
            }
        });

        __ACEPTARCONSULTA.setText("ACEPTAR");
        __ACEPTARCONSULTA.setNextFocusableComponent(__PapelNingun);

        __chkMarca.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkMarca.setForeground(new java.awt.Color(255, 255, 255));
        __chkMarca.setSelected(true);
        __chkMarca.setText("Marca:");
        __chkMarca.setEnabled(false);
        __chkMarca.setNextFocusableComponent(__cmbMarca);

        __chkProveedor.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkProveedor.setForeground(new java.awt.Color(255, 255, 255));
        __chkProveedor.setSelected(true);
        __chkProveedor.setText("Proveedor:");
        __chkProveedor.setEnabled(false);
        __chkProveedor.setNextFocusableComponent(__cmbProveedor);

        __dateIni.setDateFormatString("yyyy-MM-d");
        __dateIni.setEnabled(false);
        __dateIni.setNextFocusableComponent(__chkFechaFin);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Clase de Papel"));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);

        __grpPapel.add(__Bobina);
        __Bobina.setForeground(new java.awt.Color(255, 255, 255));
        __Bobina.setText("Bobina");
        __Bobina.setNextFocusableComponent(__Hoja);
        __Bobina.setOpaque(false);
        __Bobina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __BobinaActionPerformed(evt);
            }
        });

        __grpPapel.add(__Hoja);
        __Hoja.setForeground(new java.awt.Color(255, 255, 255));
        __Hoja.setText("Hoja");
        __Hoja.setNextFocusableComponent(__optNinguno);
        __Hoja.setOpaque(false);
        __Hoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __HojaActionPerformed(evt);
            }
        });

        __grpPapel.add(__PapelNingun);
        __PapelNingun.setForeground(new java.awt.Color(255, 255, 255));
        __PapelNingun.setSelected(true);
        __PapelNingun.setText("Ninguno");
        __PapelNingun.setOpaque(false);
        __PapelNingun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __PapelNingunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__PapelNingun)
                    .addComponent(__Bobina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(__Hoja)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(__PapelNingun)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__Bobina)
                    .addComponent(__Hoja))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        __cmbProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmbProveedor.setEnabled(false);
        __cmbProveedor.setNextFocusableComponent(__chkTipoEntrada);
        __cmbProveedor.setOpaque(false);
        __cmbProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbProveedorActionPerformed(evt);
            }
        });

        __chkOrdenP.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkOrdenP.setForeground(new java.awt.Color(255, 255, 255));
        __chkOrdenP.setSelected(true);
        __chkOrdenP.setText("Orden de Produccion:");
        __chkOrdenP.setEnabled(false);
        __chkOrdenP.setNextFocusableComponent(__OrdenP);

        __OrdenC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __OrdenC.setEnabled(false);
        __OrdenC.setNextFocusableComponent(__chkProveedor);

        __chkAncho.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkAncho.setForeground(new java.awt.Color(255, 255, 255));
        __chkAncho.setSelected(true);
        __chkAncho.setText("Ancho:");
        __chkAncho.setEnabled(false);
        __chkAncho.setNextFocusableComponent(__ancho);
        __chkAncho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkAnchoActionPerformed(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Turno:"));
        jPanel11.setOpaque(false);

        __chkTurno1.setForeground(new java.awt.Color(255, 255, 255));
        __chkTurno1.setText("Turno 1");
        __chkTurno1.setEnabled(false);
        __chkTurno1.setNextFocusableComponent(__chkTurno2);
        __chkTurno1.setOpaque(false);
        __chkTurno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno1ActionPerformed(evt);
            }
        });

        __chkTurno2.setForeground(new java.awt.Color(255, 255, 255));
        __chkTurno2.setText("Turno 2");
        __chkTurno2.setEnabled(false);
        __chkTurno2.setNextFocusableComponent(__chkTurno3);
        __chkTurno2.setOpaque(false);
        __chkTurno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno2ActionPerformed(evt);
            }
        });

        __chkTurno3.setForeground(new java.awt.Color(255, 255, 255));
        __chkTurno3.setText("Turno 3");
        __chkTurno3.setEnabled(false);
        __chkTurno3.setNextFocusableComponent(__SALIRCONSULTA);
        __chkTurno3.setOpaque(false);
        __chkTurno3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkTurno3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__chkTurno3)
                    .addComponent(__chkTurno2)
                    .addComponent(__chkTurno1))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(__chkTurno1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(__chkTurno2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(__chkTurno3))
        );

        __clave.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __clave.setEnabled(false);
        __clave.setNextFocusableComponent(__chkNombrePapel);

        __chkGrsPts.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkGrsPts.setForeground(new java.awt.Color(255, 255, 255));
        __chkGrsPts.setSelected(true);
        __chkGrsPts.setText("Grs y/o Pts");
        __chkGrsPts.setEnabled(false);
        __chkGrsPts.setNextFocusableComponent(__grspts);

        __chkFechaIni.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkFechaIni.setForeground(new java.awt.Color(255, 255, 255));
        __chkFechaIni.setSelected(true);
        __chkFechaIni.setText("Fecha Inicial:");
        __chkFechaIni.setEnabled(false);
        __chkFechaIni.setNextFocusableComponent(__dateIni);

        __chkPropietario.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkPropietario.setForeground(new java.awt.Color(255, 255, 255));
        __chkPropietario.setSelected(true);
        __chkPropietario.setText("Propietario:");
        __chkPropietario.setEnabled(false);
        __chkPropietario.setNextFocusableComponent(__cmbPropi);

        __chkTipoEntrada.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkTipoEntrada.setForeground(new java.awt.Color(255, 255, 255));
        __chkTipoEntrada.setSelected(true);
        __chkTipoEntrada.setText("Tipo de Entrada");
        __chkTipoEntrada.setEnabled(false);
        __chkTipoEntrada.setNextFocusableComponent(__cmbTipoEntrada);

        __cmbTipoEntrada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmbTipoEntrada.setEnabled(false);
        __cmbTipoEntrada.setNextFocusableComponent(__chkTipoSalida);
        __cmbTipoEntrada.setOpaque(false);
        __cmbTipoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbTipoEntradaActionPerformed(evt);
            }
        });

        __datefin.setDateFormatString("yyyy-MM-d");
        __datefin.setEnabled(false);
        __datefin.setNextFocusableComponent(__chkPropietario);

        __chkFechaFin.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkFechaFin.setForeground(new java.awt.Color(255, 255, 255));
        __chkFechaFin.setSelected(true);
        __chkFechaFin.setText("Fecha Final:");
        __chkFechaFin.setEnabled(false);
        __chkFechaFin.setNextFocusableComponent(__datefin);

        __cmbTipoSalida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona....." }));
        __cmbTipoSalida.setEnabled(false);
        __cmbTipoSalida.setNextFocusableComponent(__chkTurno1);
        __cmbTipoSalida.setOpaque(false);
        __cmbTipoSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __cmbTipoSalidaActionPerformed(evt);
            }
        });

        __chkTipoSalida.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkTipoSalida.setForeground(new java.awt.Color(255, 255, 255));
        __chkTipoSalida.setSelected(true);
        __chkTipoSalida.setText("Tipo de Salida");
        __chkTipoSalida.setEnabled(false);
        __chkTipoSalida.setNextFocusableComponent(__cmbTipoSalida);

        __documento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __documento.setEnabled(false);
        __documento.setNextFocusableComponent(__chkOrdenP);

        __chkDocumento.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __chkDocumento.setForeground(new java.awt.Color(255, 255, 255));
        __chkDocumento.setSelected(true);
        __chkDocumento.setText("Documento:");
        __chkDocumento.setEnabled(false);
        __chkDocumento.setNextFocusableComponent(__documento);
        __chkDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __chkDocumentoActionPerformed(evt);
            }
        });

        __foliohasta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __foliohasta.setEnabled(false);
        __foliohasta.setNextFocusableComponent(__chkDocumento);

        jLabel1.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hasta:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(__chkClavePapel)
                                .addGap(2, 2, 2)
                                .addComponent(__clave, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(__chkPropietario)
                                .addGap(2, 2, 2)
                                .addComponent(__cmbPropi, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(__chkProveedor)
                                .addGap(5, 5, 5)
                                .addComponent(__cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(__chkNombrePapel)
                                .addGap(3, 3, 3)
                                .addComponent(__cmbNombrePapel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(__chkKiloHoja)
                                .addGap(2, 2, 2)
                                .addComponent(__cmbKiloHoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(__kilohojas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(__chkTipoEntrada)
                                .addGap(5, 5, 5)
                                .addComponent(__cmbTipoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(__chkAncho)
                                .addGap(7, 7, 7)
                                .addComponent(__ancho, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(167, 167, 167)
                                .addComponent(__chkBobinaPaq)
                                .addGap(2, 2, 2)
                                .addComponent(__cmbBobinaPaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(__bobinapaq, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(__chkTipoSalida)
                                .addGap(7, 7, 7)
                                .addComponent(__cmbTipoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(__chkMarca)
                                .addGap(11, 11, 11)
                                .addComponent(__cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(__chkOrdenC)
                                .addGap(3, 3, 3)
                                .addComponent(__OrdenC, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(__SALIRCONSULTA)
                                .addGap(119, 119, 119)
                                .addComponent(__ACEPTARCONSULTA))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(__chkAlto)
                                        .addGap(11, 11, 11)
                                        .addComponent(__alto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(__grspts, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(__chkGrsPts)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(__chkColor)
                                        .addGap(11, 11, 11)
                                        .addComponent(__cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(__chkDocumento))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(__chkOrdenP)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(__OrdenP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(__documento, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(__chkFolio)
                                        .addGap(7, 7, 7)
                                        .addComponent(__folio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(__foliohasta, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(__etqFechaConMov))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142)
                                .addComponent(__chkFechaIni)
                                .addGap(5, 5, 5)
                                .addComponent(__dateIni, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(__chkFechaFin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(__datefin, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(__etqFechaConMov))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(__chkFechaIni)
                            .addComponent(__dateIni, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__datefin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__chkFechaFin)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(__chkClavePapel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(__clave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(__chkPropietario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(__cmbPropi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(__chkProveedor)
                    .addComponent(__cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__chkNombrePapel)
                    .addComponent(__cmbNombrePapel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(__chkKiloHoja))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(__cmbKiloHoja, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(__kilohojas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(__chkTipoEntrada)
                    .addComponent(__cmbTipoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(__chkAncho))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(__ancho, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(__chkBobinaPaq))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(__cmbBobinaPaq, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(__bobinapaq, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(__chkTipoSalida))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(__cmbTipoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__chkAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__alto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__grspts, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__chkGrsPts, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__chkColor)
                                    .addComponent(__cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__chkFolio)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(__folio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(__foliohasta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(__chkDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(__chkOrdenP))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(__documento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(__OrdenP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__chkMarca)
                    .addComponent(__cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__SALIRCONSULTA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__ACEPTARCONSULTA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(__chkOrdenC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__OrdenC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Movimiento", jPanel1);

        __MenuConsulta.setOpaque(false);

        __Archivo.setText("Archivo");

        __menuMovimientosPapel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        __menuMovimientosPapel.setText("Movimientos de Papel");
        __Archivo.add(__menuMovimientosPapel);

        __menuRegresar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        __menuRegresar.setText("Regresar al Menú Anterior");
        __menuRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuRegresarActionPerformed(evt);
            }
        });
        __Archivo.add(__menuRegresar);

        __menuAltaPapel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        __menuAltaPapel.setText("Alta de Papel");
        __menuAltaPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuAltaPapelActionPerformed(evt);
            }
        });
        __Archivo.add(__menuAltaPapel);

        __menuGeneraReporte.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        __menuGeneraReporte.setText("Generar un Reporte...");
        __Archivo.add(__menuGeneraReporte);

        __MenuAbrirArchivo3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        __MenuAbrirArchivo3.setText("Abrir Archivo...");
        __MenuAbrirArchivo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __MenuAbrirArchivo3ActionPerformed(evt);
            }
        });
        __Archivo.add(__MenuAbrirArchivo3);

        __CerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        __CerrarSesion.setText("Cerrar Sesión");
        __CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __CerrarSesionActionPerformed(evt);
            }
        });
        __Archivo.add(__CerrarSesion);

        __menuSalirSistema.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        __menuSalirSistema.setText("Salir del Sistema");
        __Archivo.add(__menuSalirSistema);

        __MenuConsulta.add(__Archivo);

        __Edicion.setText("Edición");

        __menuEdiCambiarFecha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        __menuEdiCambiarFecha.setText("Cambiar Fecha del Sistema");
        __menuEdiCambiarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuEdiCambiarFechaActionPerformed(evt);
            }
        });
        __Edicion.add(__menuEdiCambiarFecha);

        __menuEdiNewUsuario.setText("Nuevo Usuario...");
        __Edicion.add(__menuEdiNewUsuario);

        __menuEdiCambiarContraseña.setText("Cambiar mi Contraseña");
        __menuEdiCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuEdiCambiarContraseñaActionPerformed(evt);
            }
        });
        __Edicion.add(__menuEdiCambiarContraseña);

        __menuEdiReporteUsuario.setText("Reporte de Usuarios");
        __Edicion.add(__menuEdiReporteUsuario);

        __menucerrarsesiones.setText("Cerar Todas las Sesiones");
        __Edicion.add(__menucerrarsesiones);

        __menuEdiAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.CTRL_MASK));
        __menuEdiAcerca.setText("Acerca de...");
        __Edicion.add(__menuEdiAcerca);

        __menuBackup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        __menuBackup.setText("Backup");
        __menuBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuBackupActionPerformed(evt);
            }
        });
        __Edicion.add(__menuBackup);

        __MenuConsulta.add(__Edicion);

        setJMenuBar(__MenuConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void __CANCELARCONMOVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___CANCELARCONMOVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___CANCELARCONMOVActionPerformed

    private void __menuEdiCambiarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuEdiCambiarFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuEdiCambiarFechaActionPerformed

    private void __CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___CerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___CerrarSesionActionPerformed

    private void __menuAltaPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuAltaPapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuAltaPapelActionPerformed

    private void __menuRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuRegresarActionPerformed

    private void __menuEdiCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuEdiCambiarContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuEdiCambiarContraseñaActionPerformed

    private void __cmbColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbColorActionPerformed

    private void __cmbPropiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbPropiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbPropiActionPerformed

    private void __cmbBobinaPaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbBobinaPaqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbBobinaPaqActionPerformed

    private void __cmbKiloHojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbKiloHojaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbKiloHojaActionPerformed

    private void __OrdenPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___OrdenPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___OrdenPActionPerformed

    private void __cmbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbMarcaActionPerformed

    private void __cmbNombrePapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbNombrePapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbNombrePapelActionPerformed

    private void __SALIRCONSULTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___SALIRCONSULTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___SALIRCONSULTAActionPerformed

    private void __BobinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___BobinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___BobinaActionPerformed

    private void __HojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___HojaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___HojaActionPerformed

    private void __cmbProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbProveedorActionPerformed

    private void __chkTurno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno1ActionPerformed

    private void __chkTurno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno2ActionPerformed

    private void __chkTurno3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkTurno3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkTurno3ActionPerformed

    private void __cmbTipoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbTipoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbTipoEntradaActionPerformed

    private void __chkClavePapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkClavePapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkClavePapelActionPerformed

    private void __cmbTipoSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___cmbTipoSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___cmbTipoSalidaActionPerformed

    private void __altoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___altoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___altoActionPerformed

    private void __PapelNingunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___PapelNingunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___PapelNingunActionPerformed

    private void __MenuAbrirArchivo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___MenuAbrirArchivo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___MenuAbrirArchivo3ActionPerformed

    private void __chkAnchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkAnchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkAnchoActionPerformed

    private void __chkDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkDocumentoActionPerformed

    private void __chkFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___chkFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___chkFolioActionPerformed

    private void __menuBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuBackupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuBackupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPapel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton __ACEPTARCONSULTA;
    public javax.swing.JMenu __Archivo;
    public javax.swing.JRadioButton __Bobina;
    public javax.swing.JButton __CANCELARCONMOV;
    public javax.swing.JMenuItem __CerrarSesion;
    public javax.swing.JMenu __Edicion;
    public javax.swing.JRadioButton __Hoja;
    public javax.swing.JMenuItem __MenuAbrirArchivo3;
    public javax.swing.JMenuBar __MenuConsulta;
    public javax.swing.JTextField __OrdenC;
    public javax.swing.JTextField __OrdenP;
    public javax.swing.JRadioButton __PapelNingun;
    public javax.swing.JButton __SALIRCONSULTA;
    public javax.swing.JTextField __alto;
    public javax.swing.JTextField __ancho;
    public javax.swing.JTextField __bobinapaq;
    public javax.swing.JCheckBox __chkAlto;
    public javax.swing.JCheckBox __chkAncho;
    public javax.swing.JCheckBox __chkBobinaPaq;
    public javax.swing.JCheckBox __chkClavePapel;
    public javax.swing.JCheckBox __chkColor;
    public javax.swing.JCheckBox __chkDocumento;
    public javax.swing.JCheckBox __chkFechaFin;
    public javax.swing.JCheckBox __chkFechaIni;
    public javax.swing.JCheckBox __chkFolio;
    public javax.swing.JCheckBox __chkGrsPts;
    public javax.swing.JCheckBox __chkKiloHoja;
    public javax.swing.JCheckBox __chkMarca;
    public javax.swing.JCheckBox __chkMarca8;
    public javax.swing.JCheckBox __chkMarca9;
    public javax.swing.JCheckBox __chkNombrePapel;
    public javax.swing.JCheckBox __chkOrdenC;
    public javax.swing.JCheckBox __chkOrdenP;
    public javax.swing.JCheckBox __chkPropietario;
    public javax.swing.JCheckBox __chkProveedor;
    public javax.swing.JCheckBox __chkTipoEntrada;
    public javax.swing.JCheckBox __chkTipoSalida;
    public javax.swing.JCheckBox __chkTurno1;
    public javax.swing.JCheckBox __chkTurno2;
    public javax.swing.JCheckBox __chkTurno3;
    public javax.swing.JTextField __clave;
    public javax.swing.JTextField __clvDesdeMov2;
    public javax.swing.JComboBox __cmbBobinaPaq;
    public javax.swing.JComboBox __cmbColor;
    public javax.swing.JComboBox __cmbKiloHoja;
    public javax.swing.JComboBox __cmbMarca;
    public javax.swing.JComboBox __cmbNombrePapel;
    public javax.swing.JComboBox __cmbPropi;
    public javax.swing.JComboBox __cmbProveedor;
    public javax.swing.JComboBox __cmbTipoEntrada;
    public javax.swing.JComboBox __cmbTipoSalida;
    public com.toedter.calendar.JDateChooser __dateDesdeMov;
    public com.toedter.calendar.JDateChooser __dateDesdeMov1;
    public com.toedter.calendar.JDateChooser __dateIni;
    public com.toedter.calendar.JDateChooser __datefin;
    public javax.swing.JTextField __documento;
    public javax.swing.JLabel __etqFechaConMov;
    public javax.swing.JTextField __folio;
    public javax.swing.JTextField __foliohasta;
    private javax.swing.ButtonGroup __grpMovimiento;
    private javax.swing.ButtonGroup __grpPapel;
    public javax.swing.JTextField __grspts;
    public javax.swing.JTextField __kilohojas;
    public javax.swing.JMenuItem __menuAltaPapel;
    public javax.swing.JMenuItem __menuBackup;
    public javax.swing.JMenuItem __menuEdiAcerca;
    public javax.swing.JMenuItem __menuEdiCambiarContraseña;
    public javax.swing.JMenuItem __menuEdiCambiarFecha;
    public javax.swing.JMenuItem __menuEdiNewUsuario;
    public javax.swing.JMenuItem __menuEdiReporteUsuario;
    public javax.swing.JMenuItem __menuGeneraReporte;
    public javax.swing.JMenuItem __menuMovimientosPapel;
    public javax.swing.JMenuItem __menuRegresar;
    public javax.swing.JMenuItem __menuSalirSistema;
    public javax.swing.JMenuItem __menucerrarsesiones;
    public javax.swing.JRadioButton __optEntrada;
    public javax.swing.JRadioButton __optNinguno;
    public javax.swing.JRadioButton __optSalida;
    public javax.swing.JRadioButton __optSalidaInterna;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
