/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import java.awt.Dimension;

/**
 *
 * @author Rodrigo
 */
public class ConsumoTotal extends javax.swing.JFrame {

    /**
     * Creates new form ConsumoTotal
     */
    public ConsumoTotal() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        Fondo fondo = new Fondo();
        Dimension size = this.getSize();
        fondo.setSize(size);
        add(fondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OPDesde = new javax.swing.JTextField();
        __etqFechaIni = new javax.swing.JLabel();
        __etqFechaIni1 = new javax.swing.JLabel();
        __etqFechaIni2 = new javax.swing.JLabel();
        __ACEPTAR = new javax.swing.JButton();
        __SALIR = new javax.swing.JButton();
        __dateIni = new com.toedter.calendar.JDateChooser();
        __datefin = new com.toedter.calendar.JDateChooser();
        __etqFechaIni3 = new javax.swing.JLabel();
        __etqFechaIni4 = new javax.swing.JLabel();
        __etqFechaIni5 = new javax.swing.JLabel();
        OPHasta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        OPDesde.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        OPDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPDesdeActionPerformed(evt);
            }
        });

        __etqFechaIni.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqFechaIni.setForeground(new java.awt.Color(255, 255, 255));
        __etqFechaIni.setText("Desde:");

        __etqFechaIni1.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqFechaIni1.setForeground(new java.awt.Color(255, 255, 255));
        __etqFechaIni1.setText("Hasta:");

        __etqFechaIni2.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqFechaIni2.setForeground(new java.awt.Color(255, 255, 255));
        __etqFechaIni2.setText("Hasta:");

        __ACEPTAR.setText("ACEPTAR");
        __ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __ACEPTARActionPerformed(evt);
            }
        });

        __SALIR.setText("CANCELAR");
        __SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __SALIRActionPerformed(evt);
            }
        });

        __dateIni.setDateFormatString("yyyy-MM-d");

        __datefin.setDateFormatString("yyyy-MM-d");

        __etqFechaIni3.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqFechaIni3.setForeground(new java.awt.Color(255, 255, 255));
        __etqFechaIni3.setText("Fecha:");

        __etqFechaIni4.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqFechaIni4.setForeground(new java.awt.Color(255, 255, 255));
        __etqFechaIni4.setText("Desde:");

        __etqFechaIni5.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqFechaIni5.setForeground(new java.awt.Color(255, 255, 255));
        __etqFechaIni5.setText("Orden de Produccion");

        OPHasta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        OPHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPHastaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(__etqFechaIni5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(__etqFechaIni4)
                        .addGap(213, 213, 213)
                        .addComponent(__etqFechaIni1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OPDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(OPHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(__etqFechaIni)
                        .addGap(97, 97, 97)
                        .addComponent(__etqFechaIni3)
                        .addGap(83, 83, 83)
                        .addComponent(__etqFechaIni2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(__dateIni, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(__datefin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(__SALIR)
                        .addGap(245, 245, 245)
                        .addComponent(__ACEPTAR)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(__etqFechaIni5)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__etqFechaIni4)
                    .addComponent(__etqFechaIni1))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OPDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OPHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(__etqFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(__etqFechaIni3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(__etqFechaIni2)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__dateIni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__datefin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__ACEPTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OPDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPDesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OPDesdeActionPerformed

    private void __ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___ACEPTARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___ACEPTARActionPerformed

    private void __SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___SALIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___SALIRActionPerformed

    private void OPHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPHastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OPHastaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsumoTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsumoTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsumoTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsumoTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsumoTotal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField OPDesde;
    public javax.swing.JTextField OPHasta;
    public javax.swing.JButton __ACEPTAR;
    public javax.swing.JButton __SALIR;
    public com.toedter.calendar.JDateChooser __dateIni;
    public com.toedter.calendar.JDateChooser __datefin;
    public javax.swing.JLabel __etqFechaIni;
    public javax.swing.JLabel __etqFechaIni1;
    public javax.swing.JLabel __etqFechaIni2;
    public javax.swing.JLabel __etqFechaIni3;
    public javax.swing.JLabel __etqFechaIni4;
    public javax.swing.JLabel __etqFechaIni5;
    // End of variables declaration//GEN-END:variables
}
