/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Favorito
 */
public class Inventarios extends javax.swing.JFrame {

    /**
     * Creates new form Inventarios
     */
    public Inventarios() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        Fondo fondo = new Fondo();
        Dimension size = this.getSize();
        fondo.setSize(size);
        add(fondo);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/logo.png"));
        return retValue;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        __grpClasePapel = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        __etqFecha = new javax.swing.JLabel();
        __RBobina = new javax.swing.JButton();
        __RHojas = new javax.swing.JButton();
        __RSalidaH = new javax.swing.JButton();
        __RSalidaB = new javax.swing.JButton();
        __SALIR = new javax.swing.JButton();
        __etqTotal = new javax.swing.JLabel();
        __etqTotal1 = new javax.swing.JLabel();
        __etqTotal2 = new javax.swing.JLabel();
        __etqTotal4 = new javax.swing.JLabel();
        __REntradaB = new javax.swing.JButton();
        __etqTotal5 = new javax.swing.JLabel();
        __etqTotal6 = new javax.swing.JLabel();
        __REntradaH = new javax.swing.JButton();
        __OP = new javax.swing.JButton();
        __etqTotal8 = new javax.swing.JLabel();
        __etqTotal9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        __etqTotal3 = new javax.swing.JLabel();
        __RSalidaG = new javax.swing.JButton();
        __etqTotal7 = new javax.swing.JLabel();
        __RFinanzas = new javax.swing.JButton();
        __etqTotal10 = new javax.swing.JLabel();
        __etqTotal11 = new javax.swing.JLabel();
        __CONSUMOTOTALOP = new javax.swing.JButton();
        __etqTotal12 = new javax.swing.JLabel();
        __etqTotal13 = new javax.swing.JLabel();
        __OPHojas = new javax.swing.JButton();
        __etqTotal14 = new javax.swing.JLabel();
        __TraspasoBH = new javax.swing.JButton();
        __MenuInventario = new javax.swing.JMenuBar();
        __Archivo = new javax.swing.JMenu();
        __menuMovimientosPapel = new javax.swing.JMenuItem();
        __menuRegresar = new javax.swing.JMenuItem();
        __menuAltaPapel = new javax.swing.JMenuItem();
        __menuconsulta = new javax.swing.JMenuItem();
        __MenuAbrirArchivo = new javax.swing.JMenuItem();
        __CerrarSesion = new javax.swing.JMenuItem();
        __menuSalirSistema = new javax.swing.JMenuItem();
        __Edicion = new javax.swing.JMenu();
        __menuEdiCambiarFecha = new javax.swing.JMenuItem();
        __menuEdiNewUsuario = new javax.swing.JMenuItem();
        __menuEdiCambiarContraseña = new javax.swing.JMenuItem();
        __menuEdiReporteUsuario = new javax.swing.JMenuItem();
        __menuEdiAcerca = new javax.swing.JMenuItem();
        __menuBackup = new javax.swing.JMenuItem();
        __menuDatos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Inventario Inicial");
        setIconImage(getIconImage());

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Reportes Especificos ");

        __etqFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        __etqFecha.setForeground(new java.awt.Color(255, 255, 255));
        __etqFecha.setText("DD/MM/AAAA");

        __RBobina.setText("Inventario Bobina");
        __RBobina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __RBobinaActionPerformed(evt);
            }
        });

        __RHojas.setText("Inventario Hoja");
        __RHojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __RHojasActionPerformed(evt);
            }
        });

        __RSalidaH.setText("Salida de Hojas");

        __RSalidaB.setText("Salida de Bobinas");

        __SALIR.setText("Salir");

        __etqTotal.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqTotal.setForeground(new java.awt.Color(255, 255, 255));
        __etqTotal.setText("Generar Reporte de Bobinas");

        __etqTotal1.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqTotal1.setForeground(new java.awt.Color(255, 255, 255));
        __etqTotal1.setText("Generar Reporte de Hojas");

        __etqTotal2.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqTotal2.setForeground(new java.awt.Color(255, 255, 255));
        __etqTotal2.setText("Generar Reporte de Salida de Hojas");

        __etqTotal4.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqTotal4.setForeground(new java.awt.Color(255, 255, 255));
        __etqTotal4.setText("Generar Reporte de Salida de Bobinas");

        __REntradaB.setText("Entrada de Bobinas");
        __REntradaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __REntradaBActionPerformed(evt);
            }
        });

        __etqTotal5.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqTotal5.setForeground(new java.awt.Color(255, 255, 255));
        __etqTotal5.setText("Generar Reporte de Entrada de Bobinas");

        __etqTotal6.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqTotal6.setForeground(new java.awt.Color(255, 255, 255));
        __etqTotal6.setText("Generar Reporte de Entrada de Hojas");

        __REntradaH.setText("Entrada de Hojas");

        __OP.setText("Orden de Producción");

        __etqTotal8.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqTotal8.setForeground(new java.awt.Color(255, 255, 255));
        __etqTotal8.setText("Generar Reporte por Orden de Produccion");

        __etqTotal9.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqTotal9.setForeground(new java.awt.Color(255, 255, 255));
        __etqTotal9.setText("& Pliego");

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Generales del Almacén");

        __etqTotal3.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqTotal3.setForeground(new java.awt.Color(255, 255, 255));
        __etqTotal3.setText("Generar Reporte de Salida Generales");

        __RSalidaG.setText("Salidas");

        __etqTotal7.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqTotal7.setForeground(new java.awt.Color(255, 255, 255));
        __etqTotal7.setText("Tarjeta de Inventario");

        __RFinanzas.setText("Reporte Finanzas");

        __etqTotal10.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqTotal10.setForeground(new java.awt.Color(255, 255, 255));
        __etqTotal10.setText("Consumo Total por Orden de Produccion");

        __etqTotal11.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqTotal11.setForeground(new java.awt.Color(255, 255, 255));
        __etqTotal11.setText("Bobina");

        __CONSUMOTOTALOP.setText("Consumo Total");
        __CONSUMOTOTALOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __CONSUMOTOTALOPActionPerformed(evt);
            }
        });

        __etqTotal12.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqTotal12.setForeground(new java.awt.Color(255, 255, 255));
        __etqTotal12.setText("Generar Reporte por Orden de Produccion");

        __etqTotal13.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqTotal13.setForeground(new java.awt.Color(255, 255, 255));
        __etqTotal13.setText("Hojas");

        __OPHojas.setText("Orden de Producción");

        __etqTotal14.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqTotal14.setForeground(new java.awt.Color(255, 255, 255));
        __etqTotal14.setText("Generar Reporte de Traspasos");

        __TraspasoBH.setText("Traspaso");

        __Archivo.setText("Archivo");

        __menuMovimientosPapel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        __menuMovimientosPapel.setText("Movimientos de Papel");
        __Archivo.add(__menuMovimientosPapel);

        __menuRegresar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        __menuRegresar.setText("Regresar al Menú Anterior");
        __menuRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuRegresarActionPerformed(evt);
            }
        });
        __Archivo.add(__menuRegresar);

        __menuAltaPapel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        __menuAltaPapel.setText("Alta de Papel");
        __menuAltaPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuAltaPapelActionPerformed(evt);
            }
        });
        __Archivo.add(__menuAltaPapel);

        __menuconsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        __menuconsulta.setText("Consultas");
        __Archivo.add(__menuconsulta);

        __MenuAbrirArchivo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        __MenuAbrirArchivo.setText("Abrir Archivo...");
        __MenuAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __MenuAbrirArchivoActionPerformed(evt);
            }
        });
        __Archivo.add(__MenuAbrirArchivo);

        __CerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        __CerrarSesion.setText("Cerrar Sesión");
        __CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __CerrarSesionActionPerformed(evt);
            }
        });
        __Archivo.add(__CerrarSesion);

        __menuSalirSistema.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        __menuSalirSistema.setText("Salir del Sistema");
        __Archivo.add(__menuSalirSistema);

        __MenuInventario.add(__Archivo);

        __Edicion.setText("Edicion");

        __menuEdiCambiarFecha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        __menuEdiCambiarFecha.setText("Cambiar Fecha del Sistema");
        __menuEdiCambiarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuEdiCambiarFechaActionPerformed(evt);
            }
        });
        __Edicion.add(__menuEdiCambiarFecha);

        __menuEdiNewUsuario.setText("Nuevo Usuario...");
        __Edicion.add(__menuEdiNewUsuario);

        __menuEdiCambiarContraseña.setText("Cambiar Contraseña");
        __Edicion.add(__menuEdiCambiarContraseña);

        __menuEdiReporteUsuario.setText("Reporte de Usuarios");
        __Edicion.add(__menuEdiReporteUsuario);

        __menuEdiAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.CTRL_MASK));
        __menuEdiAcerca.setText("Acerca de...");
        __Edicion.add(__menuEdiAcerca);

        __menuBackup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        __menuBackup.setText("Backup");
        __menuBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuBackupActionPerformed(evt);
            }
        });
        __Edicion.add(__menuBackup);

        __menuDatos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        __menuDatos.setText("Listar Clientes, Proveedores y Propietarios");
        __menuDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __menuDatosActionPerformed(evt);
            }
        });
        __Edicion.add(__menuDatos);

        __MenuInventario.add(__Edicion);

        setJMenuBar(__MenuInventario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(__etqTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(__etqTotal1)
                        .addGap(107, 107, 107)
                        .addComponent(__etqTotal14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(__etqTotal8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(__etqTotal9)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(__etqTotal13))
                            .addComponent(__etqTotal12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(__OP, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(__OPHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(__etqTotal10)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(__etqTotal11))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(__SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(__etqTotal4)
                            .addGap(58, 58, 58)
                            .addComponent(__etqTotal2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(__etqTotal3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addGap(212, 212, 212)
                            .addComponent(__etqFecha)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(__etqTotal5)
                            .addGap(57, 57, 57)
                            .addComponent(__etqTotal6)
                            .addGap(112, 112, 112)
                            .addComponent(__etqTotal7))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(77, 77, 77)
                                    .addComponent(__REntradaB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(158, 158, 158)
                                    .addComponent(__REntradaH, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(76, 76, 76)
                                    .addComponent(__RBobina, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(__RHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(161, 161, 161)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(__RFinanzas, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(__TraspasoBH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(__CONSUMOTOTALOP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(__RSalidaB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160)
                                .addComponent(__RSalidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(157, 157, 157)
                                .addComponent(__RSalidaG, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(__etqFecha)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(__etqTotal)
                            .addComponent(__etqTotal1)
                            .addComponent(__etqTotal14))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(__RHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(__TraspasoBH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(__RBobina, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(__etqTotal5)
                            .addComponent(__etqTotal6)
                            .addComponent(__etqTotal7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__REntradaH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__RFinanzas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(__REntradaB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__etqTotal4)
                                    .addComponent(__etqTotal2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(__etqTotal3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(__RSalidaB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__RSalidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(__RSalidaG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(__etqTotal8)
                            .addComponent(__etqTotal12)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__etqTotal9)
                                    .addComponent(__etqTotal13))))
                        .addGap(7, 7, 7)
                        .addComponent(__OP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(__OPHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(__etqTotal10)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(__etqTotal11)))
                .addGap(7, 7, 7)
                .addComponent(__CONSUMOTOTALOP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(__SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void __menuRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuRegresarActionPerformed

    private void __menuAltaPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuAltaPapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuAltaPapelActionPerformed

    private void __CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___CerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___CerrarSesionActionPerformed

    private void __menuEdiCambiarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuEdiCambiarFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuEdiCambiarFechaActionPerformed

    private void __MenuAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___MenuAbrirArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___MenuAbrirArchivoActionPerformed

    private void __RBobinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___RBobinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___RBobinaActionPerformed

    private void __RHojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___RHojasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___RHojasActionPerformed

    private void __REntradaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___REntradaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___REntradaBActionPerformed

    private void __CONSUMOTOTALOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___CONSUMOTOTALOPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___CONSUMOTOTALOPActionPerformed

    private void __menuBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuBackupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuBackupActionPerformed

    private void __menuDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___menuDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___menuDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventarios().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu __Archivo;
    public javax.swing.JButton __CONSUMOTOTALOP;
    public javax.swing.JMenuItem __CerrarSesion;
    public javax.swing.JMenu __Edicion;
    public javax.swing.JMenuItem __MenuAbrirArchivo;
    public javax.swing.JMenuBar __MenuInventario;
    public javax.swing.JButton __OP;
    public javax.swing.JButton __OPHojas;
    public javax.swing.JButton __RBobina;
    public javax.swing.JButton __REntradaB;
    public javax.swing.JButton __REntradaH;
    public javax.swing.JButton __RFinanzas;
    public javax.swing.JButton __RHojas;
    public javax.swing.JButton __RSalidaB;
    public javax.swing.JButton __RSalidaG;
    public javax.swing.JButton __RSalidaH;
    public javax.swing.JButton __SALIR;
    public javax.swing.JButton __TraspasoBH;
    public javax.swing.JLabel __etqFecha;
    public javax.swing.JLabel __etqTotal;
    public javax.swing.JLabel __etqTotal1;
    public javax.swing.JLabel __etqTotal10;
    public javax.swing.JLabel __etqTotal11;
    public javax.swing.JLabel __etqTotal12;
    public javax.swing.JLabel __etqTotal13;
    public javax.swing.JLabel __etqTotal14;
    public javax.swing.JLabel __etqTotal2;
    public javax.swing.JLabel __etqTotal3;
    public javax.swing.JLabel __etqTotal4;
    public javax.swing.JLabel __etqTotal5;
    public javax.swing.JLabel __etqTotal6;
    public javax.swing.JLabel __etqTotal7;
    public javax.swing.JLabel __etqTotal8;
    public javax.swing.JLabel __etqTotal9;
    private javax.swing.ButtonGroup __grpClasePapel;
    public javax.swing.JMenuItem __menuAltaPapel;
    public javax.swing.JMenuItem __menuBackup;
    public javax.swing.JMenuItem __menuDatos;
    public javax.swing.JMenuItem __menuEdiAcerca;
    public javax.swing.JMenuItem __menuEdiCambiarContraseña;
    public javax.swing.JMenuItem __menuEdiCambiarFecha;
    public javax.swing.JMenuItem __menuEdiNewUsuario;
    public javax.swing.JMenuItem __menuEdiReporteUsuario;
    public javax.swing.JMenuItem __menuMovimientosPapel;
    public javax.swing.JMenuItem __menuRegresar;
    public javax.swing.JMenuItem __menuSalirSistema;
    public javax.swing.JMenuItem __menuconsulta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
