/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Rodrigo
 */
public class NewProveedor extends javax.swing.JFrame {

    /**
     * Creates new form NewProveedor
     */
    public NewProveedor() {
        initComponents();
        Fondo fondo = new Fondo();
        Dimension size = this.getSize();
        fondo.setSize(size);
        add(fondo);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        __NombreProveedor = new javax.swing.JTextField();
        __etqAlto_ = new javax.swing.JLabel();
        ProveCli = new javax.swing.JLabel();
        __etqAlto_1 = new javax.swing.JLabel();
        __etqAlto_2 = new javax.swing.JLabel();
        __etqAlto_3 = new javax.swing.JLabel();
        __TelefonoNProveedor = new javax.swing.JTextField();
        __DireccionProveedor = new javax.swing.JTextField();
        __RFC = new javax.swing.JTextField();
        __CANCELARPROVEEDOR = new javax.swing.JButton();
        __ACEPTARPROVEEDOR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        __NombreProveedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        __etqAlto_.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqAlto_.setForeground(new java.awt.Color(255, 255, 255));
        __etqAlto_.setText("Nombre:");

        ProveCli.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        ProveCli.setForeground(new java.awt.Color(255, 255, 0));
        ProveCli.setText("Nuevo Proveedor");

        __etqAlto_1.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqAlto_1.setForeground(new java.awt.Color(255, 255, 255));
        __etqAlto_1.setText("Dirección:");

        __etqAlto_2.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqAlto_2.setForeground(new java.awt.Color(255, 255, 255));
        __etqAlto_2.setText("Telefono:");

        __etqAlto_3.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __etqAlto_3.setForeground(new java.awt.Color(255, 255, 255));
        __etqAlto_3.setText("RFC:");

        __TelefonoNProveedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        __DireccionProveedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        __RFC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        __RFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __RFCActionPerformed(evt);
            }
        });

        __CANCELARPROVEEDOR.setText("Cancelar");
        __CANCELARPROVEEDOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __CANCELARPROVEEDORActionPerformed(evt);
            }
        });

        __ACEPTARPROVEEDOR.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(__etqAlto_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(__NombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(__etqAlto_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(__TelefonoNProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(__etqAlto_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(__RFC, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(__etqAlto_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(__DireccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(ProveCli))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(__CANCELARPROVEEDOR)
                        .addGap(101, 101, 101)
                        .addComponent(__ACEPTARPROVEEDOR)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(ProveCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__etqAlto_)
                    .addComponent(__NombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__DireccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__etqAlto_1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__TelefonoNProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__etqAlto_2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__RFC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(__etqAlto_3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__CANCELARPROVEEDOR)
                    .addComponent(__ACEPTARPROVEEDOR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void __RFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___RFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___RFCActionPerformed

    private void __CANCELARPROVEEDORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___CANCELARPROVEEDORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___CANCELARPROVEEDORActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProveedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ProveCli;
    public javax.swing.JButton __ACEPTARPROVEEDOR;
    public javax.swing.JButton __CANCELARPROVEEDOR;
    public javax.swing.JTextField __DireccionProveedor;
    public javax.swing.JTextField __NombreProveedor;
    public javax.swing.JTextField __RFC;
    public javax.swing.JTextField __TelefonoNProveedor;
    public javax.swing.JLabel __etqAlto_;
    public javax.swing.JLabel __etqAlto_1;
    public javax.swing.JLabel __etqAlto_2;
    public javax.swing.JLabel __etqAlto_3;
    // End of variables declaration//GEN-END:variables
}
