/*
 * To change this template, choose Tools | Templates
 * and op
            @Override
            public JFormattedTextField.AbstractFormatter getFormatter(JFormattedTextField tf) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }n the template in the editor.
 */
package Vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Rodrigo
 */
public class Tiro extends javax.swing.JFrame {

    public String op;
    /**
     * Creates new form Tiro
     */
    public Tiro() {
        initComponents();
        Fondo fondo = new Fondo();
        Dimension size = this.getSize();
        fondo.setSize(size);
        add(fondo);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        __EstandarProduccionXHora = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        __ContadorRotativas = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        __TiempoRealProduccion = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        __TotalPliegos = new javax.swing.JTextField();
        __FechaFinal = new com.toedter.calendar.JDateChooser();
        __FechaInicial = new com.toedter.calendar.JDateChooser();
        __CANCELARTIRO = new javax.swing.JButton();
        __ACEPTARTIRO = new javax.swing.JButton();
        __HoraInicial = new javax.swing.JFormattedTextField();
        __HoraFinal = new javax.swing.JFormattedTextField();
        __MermaImpresion = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        jLabel17.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Porcentaje Merma de Impresión:");

        jLabel18.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Fecha Inicial Pliego[aaaa-mm-dd]:");

        __EstandarProduccionXHora.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __EstandarProduccionXHora.setMaximumSize(new java.awt.Dimension(10, 30));
        __EstandarProduccionXHora.setMinimumSize(new java.awt.Dimension(10, 30));
        __EstandarProduccionXHora.setName(""); // NOI18N
        __EstandarProduccionXHora.setNextFocusableComponent(__TotalPliegos);
        __EstandarProduccionXHora.setPreferredSize(new java.awt.Dimension(10, 30));
        __EstandarProduccionXHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __EstandarProduccionXHoraActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Hora Inicial del Pliego:");

        jLabel20.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Fecha Final del Pliego[aaaa-mm-dd]:");

        jLabel21.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Hora Final del Pliego:");

        jLabel22.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Estandar de Producción por Hora:");

        jLabel23.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Tiempo Real de Producción:");

        __ContadorRotativas.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __ContadorRotativas.setMaximumSize(new java.awt.Dimension(10, 30));
        __ContadorRotativas.setMinimumSize(new java.awt.Dimension(10, 30));
        __ContadorRotativas.setName(""); // NOI18N
        __ContadorRotativas.setNextFocusableComponent(__ACEPTARTIRO);
        __ContadorRotativas.setPreferredSize(new java.awt.Dimension(10, 30));
        __ContadorRotativas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __ContadorRotativasActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Total de Pliego a Imprimir:");

        __TiempoRealProduccion.setEditable(false);
        __TiempoRealProduccion.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __TiempoRealProduccion.setMaximumSize(new java.awt.Dimension(10, 30));
        __TiempoRealProduccion.setMinimumSize(new java.awt.Dimension(10, 30));
        __TiempoRealProduccion.setName(""); // NOI18N
        __TiempoRealProduccion.setPreferredSize(new java.awt.Dimension(10, 30));
        __TiempoRealProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __TiempoRealProduccionActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Contador de Rotativas:");

        __TotalPliegos.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        __TotalPliegos.setMaximumSize(new java.awt.Dimension(10, 30));
        __TotalPliegos.setMinimumSize(new java.awt.Dimension(10, 30));
        __TotalPliegos.setName(""); // NOI18N
        __TotalPliegos.setPreferredSize(new java.awt.Dimension(10, 30));
        __TotalPliegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __TotalPliegosActionPerformed(evt);
            }
        });

        __FechaFinal.setDateFormatString("yyyy-MM-d");

        __FechaInicial.setDateFormatString("yyyy-MM-d");

        __CANCELARTIRO.setText("Cancelar");
        __CANCELARTIRO.setNextFocusableComponent(__MermaImpresion);
        __CANCELARTIRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __CANCELARTIROActionPerformed(evt);
            }
        });

        __ACEPTARTIRO.setText("Aceptar");
        __ACEPTARTIRO.setNextFocusableComponent(__CANCELARTIRO);

        try {
            __HoraInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        __HoraInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __HoraInicialActionPerformed(evt);
            }
        });

        try {
            __HoraFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        __HoraFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __HoraFinalActionPerformed(evt);
            }
        });

        __MermaImpresion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        jLabel26.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(__FechaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(__MermaImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(__CANCELARTIRO)
                            .addGap(191, 191, 191)
                            .addComponent(__ACEPTARTIRO))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23)
                                .addComponent(jLabel24)
                                .addComponent(jLabel25))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(__EstandarProduccionXHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(__TiempoRealProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(__TotalPliegos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(__ContadorRotativas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(__FechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(__HoraInicial)
                                .addComponent(__HoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(__MermaImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(__FechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(__HoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(__FechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(__HoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(__EstandarProduccionXHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(__TiempoRealProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(__TotalPliegos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(__ContadorRotativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(__CANCELARTIRO)
                    .addComponent(__ACEPTARTIRO))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void __EstandarProduccionXHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___EstandarProduccionXHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___EstandarProduccionXHoraActionPerformed

    private void __ContadorRotativasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___ContadorRotativasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___ContadorRotativasActionPerformed

    private void __TiempoRealProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___TiempoRealProduccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___TiempoRealProduccionActionPerformed

    private void __TotalPliegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___TotalPliegosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___TotalPliegosActionPerformed

    private void __CANCELARTIROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___CANCELARTIROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___CANCELARTIROActionPerformed

    private void __HoraInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___HoraInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___HoraInicialActionPerformed

    private void __HoraFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___HoraFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___HoraFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tiro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton __ACEPTARTIRO;
    public javax.swing.JButton __CANCELARTIRO;
    public javax.swing.JTextField __ContadorRotativas;
    public javax.swing.JTextField __EstandarProduccionXHora;
    public com.toedter.calendar.JDateChooser __FechaFinal;
    public com.toedter.calendar.JDateChooser __FechaInicial;
    public javax.swing.JFormattedTextField __HoraFinal;
    public javax.swing.JFormattedTextField __HoraInicial;
    public javax.swing.JFormattedTextField __MermaImpresion;
    public javax.swing.JTextField __TiempoRealProduccion;
    public javax.swing.JTextField __TotalPliegos;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    // End of variables declaration//GEN-END:variables
}
